### ISSUE TITLE
Change name

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/simodels#20]
SI is taken and si is therefore not allowed under CRAN policies: https://cran.r-project.org/package=SI

Options: 

- sim
- spint
- any others?

sims is taken: https://cran.r-project.org/package=sims

**Comment by Nowosad** [comment]
**sim** is fine; **simodels** could be an alternative...

**Comment by Robinlovelace** [comment]
Thanks Jakub, I was thinking you'd have good ideas on this : ) FYI I discussed this package today with @adamdennett and @fcorowe in the context of a short chapter on SIMs. My plan: get the package tidied up and submitted to CRAN by end of the month.

**Comment by Nowosad** [comment]
https://cran.r-project.org/web/packages/changer/index.html -- I used this package to change a name of some of my packages in the past -- very straightforward

**Comment by Robinlovelace** [comment]
Nice! I will give that a try!

**Comment by fcorowe** [comment]
> **sim** is fine; **simodels** could be an alternative...

Yes, **sim** would make sense - in reference to the models. Like it!

**Comment by Robinlovelace** [comment]
Tried again with the winbuilder and... Should have checked the package name:

Conflicting package names (submitted: sim, existing: SIM [https://bioconductor.org/packages/3.15/bioc])

**Comment by Robinlovelace** [comment]
```
available::available("sim")
Urban Dictionary can contain potentially offensive results,
  should they be included? [Y]es / [N]o:
1: 
── sim ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Name valid: ✔
Available on CRAN: ✔ 
Available on Bioconductor: ✖
Available on GitHub:  ✖ 
Abbreviations: http://www.abbreviations.com/sim
Wikipedia: https://en.wikipedia.org/wiki/sim
Wiktionary: https://en.wiktionary.org/wiki/sim
Sentiment:???
```

**Comment by Robinlovelace** [comment]
simodels sounds the best of the suggestions above to me. _ is not allowed in pkg names.
si.models could work also..

**Comment by Robinlovelace** [comment]
And for completeness:

```
available::available("sim_models")
Urban Dictionary can contain potentially offensive results,
  should they be included? [Y]es / [N]o:
1: N
── sim_models ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Name valid: ✖
Available on CRAN: ✔ 
Available on Bioconductor: ✔
```

**Comment by Robinlovelace** [comment]
Reopening only as I've thought of another possibility: **tidysim**

Pros and cons:

- tidysim is shorter and captures the fact this is about data processing and 'tidying' well but implies it is a bit tied to the tidyverse (which it is with dplyr dependency and tidyeval)
- simodels implies that the package is about models, which it is not currently

Thoughts? Least of our worries atm but any feedback on this welcome!

**Comment by adamdennett** [comment]
Only one comment here - not sure if it's either for or against - but _simodel_ was the name of Stewart Fotheringham's SIM package which I think was eventually converted into visual basic by someone in Japan. At least that's where I found it. I know there are some in the community who have views about that academic. Simodels is reminiscent. How about something like _SIMple_ or variations thereof - _SIMplr_ etc.?

**Comment by Robinlovelace** [comment]
That is interesting, didn't know about simodel! I think if its in the distant past and only hardcore SIM enthusiasts know about it it's not too much of a risk. I'm not a fan of mixed uppercase lowercase words. I like simplr though!

**Comment by Robinlovelace** [comment]
But the 'does what it says on the tin' nature of simodels makes it still my fave...
